### ISSUE TITLE
as a collective, how do I know who we helped?

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/opencollective-jobs#1] opened 2016-06-09 21:42 UTC
Goal: get a list of people who submitted issues that got resolved to make it easy to contact them and ask to contribute back. 

e.g. 

```
$> contributors mochajs/mocha --type issues --closed --include-external-contributions
```

this should return an array of users. For each we should return the username, their email if any (step 1), and (step 2) the top repos that they have contributed to with their number of stars.

E.g.

```
[ 
  { user: 
    { name: 'keenwon', email: 'xxx', repos: [ 
      { repo: 'thlorenz/proxyquire', stars: 1127 }, 
      { repo: 'gotwarlost/istanbul', stars: 4516}
    ]}, 
    issues: [{ title: 'How to dynamic load config', url: 'https://github.com/mochajs/mocha/issues/2289', comments: 0}, {}]
  }, { }, { }
]
```

Notes: 
- If step 2 is too complicated, we can stop at step 1 and forget about `user.repos`
- If you can't get the list of issues for a user in a given repo, just the latest issue is good enough.

**Comment by boneskull** [comment] 2016-06-10 01:10
will look @ this tomorrow

**Comment by boneskull** [comment] 2016-06-10 20:54
@xdamman a large percentage of issues are closed as invalid.

**Comment by xdamman** [comment] 2016-06-10 20:56
Then we may need to filter only issues that have more than 2 comments.

**Comment by boneskull** [comment] 2016-06-10 21:00
> Then we may need to filter only issues that have more than 2 comments.

that still won't guarantee much, but I see what you're getting at.

here are some more ideas:
- use issue labels.  if an issue has a label such as `confirmed-bug` and it is closed, we'd count it.
- we _may_ be able to see what issues were closed via commit messages, which would be very helpful; this isn't always used, however.
- projects using [semantic-release](https://www.npmjs.com/package/semantic-release) would help here, but that's going to limit you to JS projects afaik.

question(s):
- would we filter _out_ people who opened issues where those issues have been closed by a PR authored by a non-org member?

**Comment by boneskull** [comment] 2016-06-10 21:02
for Mocha, I could pull issue #'s out of the `CHANGELOG`--though it would take some post-processing because not every item in the `CHANGELOG` references an issue; some are direct commits and others are PRs which may or may not have an associated issue.  create a mapping from that data, then pull the user info.

**Comment by boneskull** [comment] 2016-06-10 21:08
I'm going to go after reactions on closed issues to see if we can get some reliable data that way (though there may not be much of it).

**Closed as completed** 2016-06-13 23:35 UTC
